version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    networks:
      - internal
    volumes:
      - ./data/:/opt/web/
networks:
  internal:
    driver: bridge